name: winemag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - matplotlib=3.*
  - numpy=1.*
  - pandas=1.3.*
  - pip:
    - Scrapy>=1.6
    - scrapy-fake-useragent>=1.1
